const LANGUAGES = {
  tr: {
    name: 'Türkçe',
    translations: {
      // Home View
      selectedCount: 'Seçili',
      downloadBtn: 'İndir',
      clearBtn: 'Temizle',
      settingsBtn: 'Ayarlar',
      
      // Settings View
      backBtn: 'Geri',
      settingsTitle: 'Ayarlar',
      
      // General Settings
      generalSettings: 'Genel Ayarlar',
      enableExtension: 'Uzantıyı Etkinleştir',
      selectionMode: 'Seçim Modu',
      modeNormal: 'Normal',
      modeArea: 'Alan Seçimi',
      modeSameSize: 'Aynı Boyut',
      modeLarge: 'Büyük Resimler',
      
      // Image Settings
      imageSettings: 'Resim Ayarları',
      outputFormat: 'Çıktı Formatı',
      formatOriginal: 'Orijinal',
      formatJPEG: 'JPEG',
      formatPNG: 'PNG',
      formatWEBP: 'WEBP',
      jpegQuality: 'JPEG Kalitesi',
      aspectRatio: 'En-Boy Oranı',
      ratioOriginal: 'Orijinal',
      ratio1_1: '1:1 (Kare)',
      ratio4_3: '4:3',
      ratio16_9: '16:9',
      ratioCustom: 'Özel',
      cropMode: 'Kırpma Modu',
      cropFill: 'Doldur (Merkez Kırpma)',
      cropFit: 'Sığdır (Boşluk Ekle)',
      customRatio: 'Özel Oran',
      width: 'Genişlik',
      height: 'Yükseklik',
      
      // Theme Settings
      themeSettings: 'Tema Ayarları',
      themeLight: 'Açık',
      themeDark: 'Koyu',
      themeBlue: 'Mavi',
      themePink: 'Pembe',
      themePurple: 'Mor',
      themeSpotify: 'Spotify',
      themeGray: 'Gri',
      
      // Popup Settings
      popupBehavior: 'Popup Davranışı',
      keepPopupOpen: 'İşlemden sonra popup\'ı açık tut',
      clearOnDisable: 'Devre dışı bırakıldığında seçimi temizle',
      popupSize: 'Popup Boyutu',
      sizeSmall: 'Küçük (300px)',
      sizeMedium: 'Orta (380px)',
      sizeLarge: 'Büyük (450px)',
      sizeCustom: 'Özel Boyutlar',
      
      // Save Location
      saveLocation: 'Kayıt Konumu',
      alwaysAskLocation: 'Her zaman konum sor',
      saveToSubfolder: 'Alt klasöre kaydet',
      
      // Download Settings
      downloadSettings: 'İndirme Ayarları',
      filenameMode: 'Dosya Adı Modu',
      modeAuto: 'Otomatik (Başlık_001)',
      modeSequential: 'Sıralı (Img_001)',
      modeCustom: 'Özel Şablon',
      customTemplate: 'Şablon ({site}, {title}, {index} kullanın)',
      downloadAsZip: 'ZIP paketi olarak indir',
      lowPerfMode: 'Düşük Performans Modu',
      imagePreviews: 'Resim Önizlemeleri',
      uiOverlays: 'UI Katmanları',
      batchSize: 'Toplu İşlem Boyutu',
      delay: 'Gecikme (ms)',
      maxSelect: 'Maks. Seçim',
      lazyProcess: 'Tembel İşleme',
      
      // Photo Converter
      photoConverter: '🔄 Fotoğraf Dönüştürücü',
      enableConverter: 'Fotoğraf Dönüştürücüyü Etkinleştir',
      showConverterToolbar: 'Dönüştürücü Araç Çubuğunu Göster',
      defaultOutputFormat: 'Varsayılan Çıktı Formatı',
      converterQuality: 'Dönüştürücü Kalitesi',
      autoDownloadAfterConversion: 'Dönüştürmeden sonra otomatik indir',
      
      // Keyboard Shortcuts
      keyboardShortcuts: '⌨️ Klavye Kısayolları',
      enableShortcuts: 'Kısayolları etkinleştir',
      toggleSelectionMode: 'Seçim Modunu Aç/Kapat',
      selectAllImages: 'Tüm Resimleri Seç',
      clearSelection: 'Seçimi Temizle',
      downloadImages: 'Resimleri İndir',
      downloadAsZIP: 'ZIP olarak İndir',
      togglePreviews: 'Önizlemeleri Aç/Kapat',
      toggleLowPerformance: 'Düşük Performansı Aç/Kapat',
      toggleConverterToolbar: 'Dönüştürücü Araç Çubuğunu Aç/Kapat',
      resetToDefaults: 'Varsayılanlara Sıfırla',
      
      // Language Settings
      languageSettings: '🌐 Dil Ayarları',
      selectLanguage: 'Dil Seçin',
      
      // Other
      projectRepository: 'Proje Deposu',
      openGitHub: '➡️ GitHub\'ı Aç',
      version: 'Versiyon',
      
      // Converter Toolbar
      converterTitle: '🔄 Fotoğraf Dönüştürücü',
      uploadImage: '📁 Resim Yükle',
      format: 'Format:',
      quality: 'Kalite:',
      convertDownload: '⚡ Dönüştür ve İndir',
      converted: '✓ Dönüştürüldü!',
      failed: '✗ Başarısız',
      error: '✗ Hata',
      // Home Tabs
      tabGrab: 'Yakala',
      tabHistory: 'Geçmiş',
      tabCollections: 'Koleksiyonlar',
      // History
      downloadHistory: 'İndirme Geçmişi',
      clearAll: 'Tümünü Temizle',
      noDownloads: 'Henüz indirme yok',
      // Collections
      newCollectionPlaceholder: 'Yeni koleksiyon adı...',
      addCollection: '+ Ekle',
      noCollections: 'Henüz koleksiyon yok',
      addSelectedImages: 'Seçili Görselleri Buraya Ekle',
      // Cloud
      cloudUpload: 'Bulut Yükleme',
      cloudDesc: 'İndirilen görselleri buluta yükle.',
      cloudNote: 'Her sağlayıcı kendi OAuth sayfasını açar.',
      // Theme Customization
      customTheme: 'Özel Tema Rengi',
      customPrimaryColor: 'Ana Renk',
      resetColor: 'Sıfırla',
      // Walkthrough
      walkthroughTitle: 'Photo-Grab\'e Hoş Geldiniz!',
      walkthroughStep1Title: 'Görselleri Seçin',
      walkthroughStep1Desc: 'Sayfada görsellerin üzerine tıklayarak seçin. Extension Active toggle ile seçim modunu açın.',
      walkthroughStep2Title: 'İndirin veya Dönüştürün',
      walkthroughStep2Desc: 'Download tuşuyla toplu indirin. Photo Converter toggle ile sayfada dönüştürücü araç çubuğunu açın.',
      walkthroughStep3Title: 'Geçmiş ve Koleksiyonlar',
      walkthroughStep3Desc: 'History tabında indirme geçmişinizi görün. Collections ile görselleri kategorilere ayırın.',
      walkthroughNext: 'İleri',
      walkthroughDone: 'Başla!',
      walkthroughSkip: 'Atla'
    }
  },
  
  en: {
    name: 'English',
    translations: {
      selectedCount: 'Selected',
      downloadBtn: 'Download',
      clearBtn: 'Clear',
      settingsBtn: 'Settings',
      backBtn: 'Back',
      settingsTitle: 'Settings',
      generalSettings: 'General Settings',
      enableExtension: 'Enable Extension',
      selectionMode: 'Selection Mode',
      modeNormal: 'Normal',
      modeArea: 'Area Selection',
      modeSameSize: 'Same Size',
      modeLarge: 'Large Images',
      imageSettings: 'Image Settings',
      outputFormat: 'Output Format',
      formatOriginal: 'Original',
      formatJPEG: 'JPEG',
      formatPNG: 'PNG',
      formatWEBP: 'WEBP',
      jpegQuality: 'JPEG Quality',
      aspectRatio: 'Aspect Ratio',
      ratioOriginal: 'Original',
      ratio1_1: '1:1 (Square)',
      ratio4_3: '4:3',
      ratio16_9: '16:9',
      ratioCustom: 'Custom',
      cropMode: 'Crop Mode',
      cropFill: 'Fill (Center Crop)',
      cropFit: 'Fit (Add Padding)',
      customRatio: 'Custom Ratio',
      width: 'Width',
      height: 'Height',
      themeSettings: 'Theme Settings',
      themeLight: 'Light',
      themeDark: 'Dark',
      themeBlue: 'Blue',
      themePink: 'Pink',
      themePurple: 'Purple',
      themeSpotify: 'Spotify',
      themeGray: 'Gray',
      popupBehavior: 'Popup Behavior',
      keepPopupOpen: 'Keep popup open after action',
      clearOnDisable: 'Clear selection on disable',
      popupSize: 'Popup Size',
      sizeSmall: 'Small (300px)',
      sizeMedium: 'Medium (380px)',
      sizeLarge: 'Large (450px)',
      sizeCustom: 'Custom Dimensions',
      saveLocation: 'Save Location',
      alwaysAskLocation: 'Always ask for location',
      saveToSubfolder: 'Save to subfolder',
      downloadSettings: 'Download Settings',
      filenameMode: 'Filename Mode',
      modeAuto: 'Automatic (Title_001)',
      modeSequential: 'Sequential (Img_001)',
      modeCustom: 'Custom Template',
      customTemplate: 'Template (Use {site}, {title}, {index})',
      downloadAsZip: 'Download as ZIP Bundle',
      lowPerfMode: 'Low Performance Mode',
      imagePreviews: 'Image Previews',
      uiOverlays: 'UI Overlays',
      batchSize: 'Batch Size',
      delay: 'Delay (ms)',
      maxSelect: 'Max Select',
      lazyProcess: 'Lazy Process',
      photoConverter: '🔄 Photo Converter',
      enableConverter: 'Enable Photo Converter',
      showConverterToolbar: 'Show Converter Toolbar',
      defaultOutputFormat: 'Default Output Format',
      converterQuality: 'Converter Quality',
      autoDownloadAfterConversion: 'Auto-download after conversion',
      keyboardShortcuts: '⌨️ Keyboard Shortcuts',
      enableShortcuts: 'Enable shortcuts',
      toggleSelectionMode: 'Toggle Selection Mode',
      selectAllImages: 'Select All Images',
      clearSelection: 'Clear Selection',
      downloadImages: 'Download Images',
      downloadAsZIP: 'Download as ZIP',
      togglePreviews: 'Toggle Previews',
      toggleLowPerformance: 'Toggle Low Performance',
      toggleConverterToolbar: 'Toggle Converter Toolbar',
      resetToDefaults: 'Reset to Defaults',
      languageSettings: '🌐 Language Settings',
      selectLanguage: 'Select Language',
      projectRepository: 'Project Repository',
      openGitHub: '➡️ Open GitHub',
      version: 'Version',
      converterTitle: '🔄 Photo Converter',
      uploadImage: '📁 Upload Image',
      format: 'Format:',
      quality: 'Quality:',
      convertDownload: '⚡ Convert & Download',
      converted: '✓ Converted!',
      failed: '✗ Failed',
      error: '✗ Error',
      tabGrab: 'Grab',
      tabHistory: 'History',
      tabCollections: 'Collections',
      downloadHistory: 'Download History',
      clearAll: 'Clear All',
      noDownloads: 'No downloads yet',
      newCollectionPlaceholder: 'New collection name...',
      addCollection: '+ Add',
      noCollections: 'No collections yet',
      addSelectedImages: 'Add Selected Images Here',
      cloudUpload: 'Cloud Upload',
      cloudDesc: 'Upload downloaded images to cloud storage.',
      cloudNote: 'Each provider opens its own OAuth page.',
      customTheme: 'Custom Theme Color',
      customPrimaryColor: 'Primary Color',
      resetColor: 'Reset',
      walkthroughTitle: 'Welcome to Photo-Grab!',
      walkthroughStep1Title: 'Select Images',
      walkthroughStep1Desc: 'Click images on any page to select them. Use the Extension Active toggle to enable selection mode.',
      walkthroughStep2Title: 'Download or Convert',
      walkthroughStep2Desc: 'Use the Download button for bulk downloads. Toggle Photo Converter to show the converter toolbar on the page.',
      walkthroughStep3Title: 'History & Collections',
      walkthroughStep3Desc: 'View your download history in the History tab. Use Collections to organize images into categories.',
      walkthroughNext: 'Next',
      walkthroughDone: 'Get Started!',
      walkthroughSkip: 'Skip'
    }
  },
  
  ru: {
    name: 'Русский',
    translations: {
      selectedCount: 'Выбрано',
      downloadBtn: 'Скачать',
      clearBtn: 'Очистить',
      settingsBtn: 'Настройки',
      backBtn: 'Назад',
      settingsTitle: 'Настройки',
      generalSettings: 'Общие настройки',
      enableExtension: 'Включить расширение',
      selectionMode: 'Режим выбора',
      modeNormal: 'Обычный',
      modeArea: 'Выбор области',
      modeSameSize: 'Одинаковый размер',
      modeLarge: 'Большие изображения',
      imageSettings: 'Настройки изображения',
      outputFormat: 'Формат вывода',
      formatOriginal: 'Оригинал',
      formatJPEG: 'JPEG',
      formatPNG: 'PNG',
      formatWEBP: 'WEBP',
      jpegQuality: 'Качество JPEG',
      aspectRatio: 'Соотношение сторон',
      ratioOriginal: 'Оригинал',
      ratio1_1: '1:1 (Квадрат)',
      ratio4_3: '4:3',
      ratio16_9: '16:9',
      ratioCustom: 'Пользовательское',
      cropMode: 'Режим обрезки',
      cropFill: 'Заполнить (Центральная обрезка)',
      cropFit: 'Подогнать (Добавить отступы)',
      customRatio: 'Пользовательское соотношение',
      width: 'Ширина',
      height: 'Высота',
      themeSettings: 'Настройки темы',
      themeLight: 'Светлая',
      themeDark: 'Тёмная',
      themeBlue: 'Синяя',
      themePink: 'Розовая',
      themePurple: 'Фиолетовая',
      themeSpotify: 'Spotify',
      themeGray: 'Серая',
      popupBehavior: 'Поведение всплывающего окна',
      keepPopupOpen: 'Держать окно открытым после действия',
      clearOnDisable: 'Очистить выбор при отключении',
      popupSize: 'Размер всплывающего окна',
      sizeSmall: 'Маленький (300px)',
      sizeMedium: 'Средний (380px)',
      sizeLarge: 'Большой (450px)',
      sizeCustom: 'Пользовательские размеры',
      saveLocation: 'Место сохранения',
      alwaysAskLocation: 'Всегда спрашивать место',
      saveToSubfolder: 'Сохранить в подпапку',
      downloadSettings: 'Настройки загрузки',
      filenameMode: 'Режим имени файла',
      modeAuto: 'Автоматический (Заголовок_001)',
      modeSequential: 'Последовательный (Img_001)',
      modeCustom: 'Пользовательский шаблон',
      customTemplate: 'Шаблон (Используйте {site}, {title}, {index})',
      downloadAsZip: 'Скачать как ZIP-архив',
      lowPerfMode: 'Режим низкой производительности',
      imagePreviews: 'Предпросмотр изображений',
      uiOverlays: 'UI наложения',
      batchSize: 'Размер пакета',
      delay: 'Задержка (мс)',
      maxSelect: 'Макс. выбор',
      lazyProcess: 'Ленивая обработка',
      photoConverter: '🔄 Конвертер фото',
      enableConverter: 'Включить конвертер фото',
      showConverterToolbar: 'Показать панель конвертера',
      defaultOutputFormat: 'Формат вывода по умолчанию',
      converterQuality: 'Качество конвертера',
      autoDownloadAfterConversion: 'Автозагрузка после конвертации',
      keyboardShortcuts: '⌨️ Горячие клавиши',
      enableShortcuts: 'Включить горячие клавиши',
      toggleSelectionMode: 'Переключить режим выбора',
      selectAllImages: 'Выбрать все изображения',
      clearSelection: 'Очистить выбор',
      downloadImages: 'Скачать изображения',
      downloadAsZIP: 'Скачать как ZIP',
      togglePreviews: 'Переключить предпросмотр',
      toggleLowPerformance: 'Переключить низкую производительность',
      toggleConverterToolbar: 'Переключить панель конвертера',
      resetToDefaults: 'Сбросить по умолчанию',
      languageSettings: '🌐 Настройки языка',
      selectLanguage: 'Выберите язык',
      projectRepository: 'Репозиторий проекта',
      openGitHub: '➡️ Открыть GitHub',
      version: 'Версия',
      converterTitle: '🔄 Конвертер фото',
      uploadImage: '📁 Загрузить изображение',
      format: 'Формат:',
      quality: 'Качество:',
      convertDownload: '⚡ Конвертировать и скачать',
      converted: '✓ Конвертировано!',
      failed: '✗ Ошибка',
      error: '✗ Ошибка',
      tabGrab: 'Захват',
      tabHistory: 'История',
      tabCollections: 'Коллекции',
      downloadHistory: 'История загрузок',
      clearAll: 'Очистить всё',
      noDownloads: 'Загрузок пока нет',
      newCollectionPlaceholder: 'Название коллекции...',
      addCollection: '+ Добавить',
      noCollections: 'Коллекций пока нет',
      addSelectedImages: 'Добавить выбранные сюда',
      cloudUpload: 'Облачная загрузка',
      cloudDesc: 'Загрузите изображения в облачное хранилище.',
      cloudNote: 'Каждый провайдер открывает свою OAuth-страницу.',
      customTheme: 'Пользовательский цвет темы',
      customPrimaryColor: 'Основной цвет',
      resetColor: 'Сбросить',
      walkthroughTitle: 'Добро пожаловать в Photo-Grab!',
      walkthroughStep1Title: 'Выберите изображения',
      walkthroughStep1Desc: 'Нажмите на изображения на странице для их выбора. Используйте переключатель Extension Active.',
      walkthroughStep2Title: 'Загрузка или конвертация',
      walkthroughStep2Desc: 'Используйте кнопку Download для массовой загрузки. Включите Photo Converter для панели конвертера.',
      walkthroughStep3Title: 'История и коллекции',
      walkthroughStep3Desc: 'Просматривайте историю загрузок во вкладке История. Используйте Коллекции для организации.',
      walkthroughNext: 'Далее',
      walkthroughDone: 'Начать!',
      walkthroughSkip: 'Пропустить'
    }
  },
  
  fr: {
    name: 'Français',
    translations: {
      selectedCount: 'Sélectionné',
      downloadBtn: 'Télécharger',
      clearBtn: 'Effacer',
      settingsBtn: 'Paramètres',
      backBtn: 'Retour',
      settingsTitle: 'Paramètres',
      generalSettings: 'Paramètres généraux',
      enableExtension: 'Activer l\'extension',
      selectionMode: 'Mode de sélection',
      modeNormal: 'Normal',
      modeArea: 'Sélection de zone',
      modeSameSize: 'Même taille',
      modeLarge: 'Grandes images',
      imageSettings: 'Paramètres d\'image',
      outputFormat: 'Format de sortie',
      formatOriginal: 'Original',
      formatJPEG: 'JPEG',
      formatPNG: 'PNG',
      formatWEBP: 'WEBP',
      jpegQuality: 'Qualité JPEG',
      aspectRatio: 'Rapport d\'aspect',
      ratioOriginal: 'Original',
      ratio1_1: '1:1 (Carré)',
      ratio4_3: '4:3',
      ratio16_9: '16:9',
      ratioCustom: 'Personnalisé',
      cropMode: 'Mode de recadrage',
      cropFill: 'Remplir (Recadrage central)',
      cropFit: 'Ajuster (Ajouter un rembourrage)',
      customRatio: 'Rapport personnalisé',
      width: 'Largeur',
      height: 'Hauteur',
      themeSettings: 'Paramètres de thème',
      themeLight: 'Clair',
      themeDark: 'Sombre',
      themeBlue: 'Bleu',
      themePink: 'Rose',
      themePurple: 'Violet',
      themeSpotify: 'Spotify',
      themeGray: 'Gris',
      popupBehavior: 'Comportement de la popup',
      keepPopupOpen: 'Garder la popup ouverte après l\'action',
      clearOnDisable: 'Effacer la sélection lors de la désactivation',
      popupSize: 'Taille de la popup',
      sizeSmall: 'Petit (300px)',
      sizeMedium: 'Moyen (380px)',
      sizeLarge: 'Grand (450px)',
      sizeCustom: 'Dimensions personnalisées',
      saveLocation: 'Emplacement de sauvegarde',
      alwaysAskLocation: 'Toujours demander l\'emplacement',
      saveToSubfolder: 'Enregistrer dans un sous-dossier',
      downloadSettings: 'Paramètres de téléchargement',
      filenameMode: 'Mode de nom de fichier',
      modeAuto: 'Automatique (Titre_001)',
      modeSequential: 'Séquentiel (Img_001)',
      modeCustom: 'Modèle personnalisé',
      customTemplate: 'Modèle (Utilisez {site}, {title}, {index})',
      downloadAsZip: 'Télécharger en tant que bundle ZIP',
      lowPerfMode: 'Mode basse performance',
      imagePreviews: 'Aperçus d\'images',
      uiOverlays: 'Superpositions UI',
      batchSize: 'Taille du lot',
      delay: 'Délai (ms)',
      maxSelect: 'Sélection max',
      lazyProcess: 'Traitement paresseux',
      photoConverter: '🔄 Convertisseur de photos',
      enableConverter: 'Activer le convertisseur de photos',
      showConverterToolbar: 'Afficher la barre d\'outils du convertisseur',
      defaultOutputFormat: 'Format de sortie par défaut',
      converterQuality: 'Qualité du convertisseur',
      autoDownloadAfterConversion: 'Téléchargement automatique après conversion',
      keyboardShortcuts: '⌨️ Raccourcis clavier',
      enableShortcuts: 'Activer les raccourcis',
      toggleSelectionMode: 'Basculer le mode de sélection',
      selectAllImages: 'Sélectionner toutes les images',
      clearSelection: 'Effacer la sélection',
      downloadImages: 'Télécharger les images',
      downloadAsZIP: 'Télécharger en ZIP',
      togglePreviews: 'Basculer les aperçus',
      toggleLowPerformance: 'Basculer la basse performance',
      toggleConverterToolbar: 'Basculer la barre d\'outils du convertisseur',
      resetToDefaults: 'Réinitialiser par défaut',
      languageSettings: '🌐 Paramètres de langue',
      selectLanguage: 'Sélectionner la langue',
      projectRepository: 'Dépôt du projet',
      openGitHub: '➡️ Ouvrir GitHub',
      version: 'Version',
      converterTitle: '🔄 Convertisseur de photos',
      uploadImage: '📁 Télécharger une image',
      format: 'Format:',
      quality: 'Qualité:',
      convertDownload: '⚡ Convertir et télécharger',
      converted: '✓ Converti!',
      failed: '✗ Échec',
      error: '✗ Erreur',
      tabGrab: 'Capturer',
      tabHistory: 'Historique',
      tabCollections: 'Collections',
      downloadHistory: 'Historique des téléchargements',
      clearAll: 'Tout effacer',
      noDownloads: 'Aucun téléchargement',
      newCollectionPlaceholder: 'Nom de la collection...',
      addCollection: '+ Ajouter',
      noCollections: 'Aucune collection',
      addSelectedImages: 'Ajouter les images sélectionnées',
      cloudUpload: 'Upload Cloud',
      cloudDesc: 'Téléversez des images vers le stockage cloud.',
      cloudNote: 'Chaque fournisseur ouvre sa propre page OAuth.',
      customTheme: 'Couleur de thème personnalisée',
      customPrimaryColor: 'Couleur principale',
      resetColor: 'Réinitialiser',
      walkthroughTitle: 'Bienvenue sur Photo-Grab!',
      walkthroughStep1Title: 'Sélectionner des images',
      walkthroughStep1Desc: 'Cliquez sur les images pour les sélectionner. Utilisez le bouton Extension Active.',
      walkthroughStep2Title: 'Télécharger ou convertir',
      walkthroughStep2Desc: 'Utilisez le bouton Download. Activez Photo Converter pour la barre d\'outils.',
      walkthroughStep3Title: 'Historique et collections',
      walkthroughStep3Desc: 'Consultez l\'historique dans l\'onglet Historique. Utilisez Collections pour organiser.',
      walkthroughNext: 'Suivant',
      walkthroughDone: 'Commencer!',
      walkthroughSkip: 'Passer'
    }
  },
  
  es: {
    name: 'Español',
    translations: {
      selectedCount: 'Seleccionado',
      downloadBtn: 'Descargar',
      clearBtn: 'Limpiar',
      settingsBtn: 'Configuración',
      backBtn: 'Atrás',
      settingsTitle: 'Configuración',
      generalSettings: 'Configuración general',
      enableExtension: 'Activar extensión',
      selectionMode: 'Modo de selección',
      modeNormal: 'Normal',
      modeArea: 'Selección de área',
      modeSameSize: 'Mismo tamaño',
      modeLarge: 'Imágenes grandes',
      imageSettings: 'Configuración de imagen',
      outputFormat: 'Formato de salida',
      formatOriginal: 'Original',
      formatJPEG: 'JPEG',
      formatPNG: 'PNG',
      formatWEBP: 'WEBP',
      jpegQuality: 'Calidad JPEG',
      aspectRatio: 'Relación de aspecto',
      ratioOriginal: 'Original',
      ratio1_1: '1:1 (Cuadrado)',
      ratio4_3: '4:3',
      ratio16_9: '16:9',
      ratioCustom: 'Personalizado',
      cropMode: 'Modo de recorte',
      cropFill: 'Rellenar (Recorte central)',
      cropFit: 'Ajustar (Agregar relleno)',
      customRatio: 'Relación personalizada',
      width: 'Ancho',
      height: 'Alto',
      themeSettings: 'Configuración de tema',
      themeLight: 'Claro',
      themeDark: 'Oscuro',
      themeBlue: 'Azul',
      themePink: 'Rosa',
      themePurple: 'Púrpura',
      themeSpotify: 'Spotify',
      themeGray: 'Gris',
      popupBehavior: 'Comportamiento del popup',
      keepPopupOpen: 'Mantener popup abierto después de la acción',
      clearOnDisable: 'Limpiar selección al desactivar',
      popupSize: 'Tamaño del popup',
      sizeSmall: 'Pequeño (300px)',
      sizeMedium: 'Mediano (380px)',
      sizeLarge: 'Grande (450px)',
      sizeCustom: 'Dimensiones personalizadas',
      saveLocation: 'Ubicación de guardado',
      alwaysAskLocation: 'Siempre preguntar ubicación',
      saveToSubfolder: 'Guardar en subcarpeta',
      downloadSettings: 'Configuración de descarga',
      filenameMode: 'Modo de nombre de archivo',
      modeAuto: 'Automático (Título_001)',
      modeSequential: 'Secuencial (Img_001)',
      modeCustom: 'Plantilla personalizada',
      customTemplate: 'Plantilla (Use {site}, {title}, {index})',
      downloadAsZip: 'Descargar como paquete ZIP',
      lowPerfMode: 'Modo de bajo rendimiento',
      imagePreviews: 'Vistas previas de imágenes',
      uiOverlays: 'Superposiciones de UI',
      batchSize: 'Tamaño del lote',
      delay: 'Retraso (ms)',
      maxSelect: 'Selección máx',
      lazyProcess: 'Proceso perezoso',
      photoConverter: '🔄 Convertidor de fotos',
      enableConverter: 'Activar convertidor de fotos',
      showConverterToolbar: 'Mostrar barra de herramientas del convertidor',
      defaultOutputFormat: 'Formato de salida predeterminado',
      converterQuality: 'Calidad del convertidor',
      autoDownloadAfterConversion: 'Descarga automática después de la conversión',
      keyboardShortcuts: '⌨️ Atajos de teclado',
      enableShortcuts: 'Activar atajos',
      toggleSelectionMode: 'Alternar modo de selección',
      selectAllImages: 'Seleccionar todas las imágenes',
      clearSelection: 'Limpiar selección',
      downloadImages: 'Descargar imágenes',
      downloadAsZIP: 'Descargar como ZIP',
      togglePreviews: 'Alternar vistas previas',
      toggleLowPerformance: 'Alternar bajo rendimiento',
      toggleConverterToolbar: 'Alternar barra de herramientas del convertidor',
      resetToDefaults: 'Restablecer valores predeterminados',
      languageSettings: '🌐 Configuración de idioma',
      selectLanguage: 'Seleccionar idioma',
      projectRepository: 'Repositorio del proyecto',
      openGitHub: '➡️ Abrir GitHub',
      version: 'Versión',
      converterTitle: '🔄 Convertidor de fotos',
      uploadImage: '📁 Subir imagen',
      format: 'Formato:',
      quality: 'Calidad:',
      convertDownload: '⚡ Convertir y descargar',
      converted: '✓ ¡Convertido!',
      failed: '✗ Fallido',
      error: '✗ Error',
      tabGrab: 'Capturar',
      tabHistory: 'Historial',
      tabCollections: 'Colecciones',
      downloadHistory: 'Historial de descargas',
      clearAll: 'Limpiar todo',
      noDownloads: 'Sin descargas aún',
      newCollectionPlaceholder: 'Nombre de colección...',
      addCollection: '+ Agregar',
      noCollections: 'Sin colecciones aún',
      addSelectedImages: 'Agregar imágenes seleccionadas',
      cloudUpload: 'Subida en la nube',
      cloudDesc: 'Sube imágenes al almacenamiento en la nube.',
      cloudNote: 'Cada proveedor abre su propia página OAuth.',
      customTheme: 'Color de tema personalizado',
      customPrimaryColor: 'Color principal',
      resetColor: 'Restablecer',
      walkthroughTitle: '¡Bienvenido a Photo-Grab!',
      walkthroughStep1Title: 'Seleccionar imágenes',
      walkthroughStep1Desc: 'Haz clic en las imágenes para seleccionarlas. Usa el interruptor Extension Active.',
      walkthroughStep2Title: 'Descargar o convertir',
      walkthroughStep2Desc: 'Usa el botón Download. Activa Photo Converter para la barra de herramientas.',
      walkthroughStep3Title: 'Historial y colecciones',
      walkthroughStep3Desc: 'Ve el historial en la pestaña Historial. Usa Colecciones para organizar imágenes.',
      walkthroughNext: 'Siguiente',
      walkthroughDone: '¡Empezar!',
      walkthroughSkip: 'Omitir'
    }
  },
  
  de: {
    name: 'Deutsch',
    translations: {
      selectedCount: 'Ausgewählt',
      downloadBtn: 'Herunterladen',
      clearBtn: 'Löschen',
      settingsBtn: 'Einstellungen',
      backBtn: 'Zurück',
      settingsTitle: 'Einstellungen',
      generalSettings: 'Allgemeine Einstellungen',
      enableExtension: 'Erweiterung aktivieren',
      selectionMode: 'Auswahlmodus',
      modeNormal: 'Normal',
      modeArea: 'Bereichsauswahl',
      modeSameSize: 'Gleiche Größe',
      modeLarge: 'Große Bilder',
      imageSettings: 'Bildeinstellungen',
      outputFormat: 'Ausgabeformat',
      formatOriginal: 'Original',
      formatJPEG: 'JPEG',
      formatPNG: 'PNG',
      formatWEBP: 'WEBP',
      jpegQuality: 'JPEG-Qualität',
      aspectRatio: 'Seitenverhältnis',
      ratioOriginal: 'Original',
      ratio1_1: '1:1 (Quadrat)',
      ratio4_3: '4:3',
      ratio16_9: '16:9',
      ratioCustom: 'Benutzerdefiniert',
      cropMode: 'Zuschneidemodus',
      cropFill: 'Füllen (Mittelzuschnitt)',
      cropFit: 'Anpassen (Polsterung hinzufügen)',
      customRatio: 'Benutzerdefiniertes Verhältnis',
      width: 'Breite',
      height: 'Höhe',
      themeSettings: 'Theme-Einstellungen',
      themeLight: 'Hell',
      themeDark: 'Dunkel',
      themeBlue: 'Blau',
      themePink: 'Rosa',
      themePurple: 'Lila',
      themeSpotify: 'Spotify',
      themeGray: 'Grau',
      popupBehavior: 'Popup-Verhalten',
      keepPopupOpen: 'Popup nach Aktion offen halten',
      clearOnDisable: 'Auswahl beim Deaktivieren löschen',
      popupSize: 'Popup-Größe',
      sizeSmall: 'Klein (300px)',
      sizeMedium: 'Mittel (380px)',
      sizeLarge: 'Groß (450px)',
      sizeCustom: 'Benutzerdefinierte Abmessungen',
      saveLocation: 'Speicherort',
      alwaysAskLocation: 'Immer nach Speicherort fragen',
      saveToSubfolder: 'In Unterordner speichern',
      downloadSettings: 'Download-Einstellungen',
      filenameMode: 'Dateinamenmodus',
      modeAuto: 'Automatisch (Titel_001)',
      modeSequential: 'Sequenziell (Img_001)',
      modeCustom: 'Benutzerdefinierte Vorlage',
      customTemplate: 'Vorlage (Verwenden Sie {site}, {title}, {index})',
      downloadAsZip: 'Als ZIP-Paket herunterladen',
      lowPerfMode: 'Niedrigleistungsmodus',
      imagePreviews: 'Bildvorschauen',
      uiOverlays: 'UI-Überlagerungen',
      batchSize: 'Stapelgröße',
      delay: 'Verzögerung (ms)',
      maxSelect: 'Max. Auswahl',
      lazyProcess: 'Lazy-Verarbeitung',
      photoConverter: '🔄 Fotokonverter',
      enableConverter: 'Fotokonverter aktivieren',
      showConverterToolbar: 'Konverter-Symbolleiste anzeigen',
      defaultOutputFormat: 'Standard-Ausgabeformat',
      converterQuality: 'Konverterqualität',
      autoDownloadAfterConversion: 'Automatischer Download nach Konvertierung',
      keyboardShortcuts: '⌨️ Tastaturkürzel',
      enableShortcuts: 'Tastaturkürzel aktivieren',
      toggleSelectionMode: 'Auswahlmodus umschalten',
      selectAllImages: 'Alle Bilder auswählen',
      clearSelection: 'Auswahl löschen',
      downloadImages: 'Bilder herunterladen',
      downloadAsZIP: 'Als ZIP herunterladen',
      togglePreviews: 'Vorschauen umschalten',
      toggleLowPerformance: 'Niedrigleistung umschalten',
      toggleConverterToolbar: 'Konverter-Symbolleiste umschalten',
      resetToDefaults: 'Auf Standardwerte zurücksetzen',
      languageSettings: '🌐 Spracheinstellungen',
      selectLanguage: 'Sprache auswählen',
      projectRepository: 'Projekt-Repository',
      openGitHub: '➡️ GitHub öffnen',
      version: 'Version',
      converterTitle: '🔄 Fotokonverter',
      uploadImage: '📁 Bild hochladen',
      format: 'Format:',
      quality: 'Qualität:',
      convertDownload: '⚡ Konvertieren und herunterladen',
      converted: '✓ Konvertiert!',
      failed: '✗ Fehlgeschlagen',
      error: '✗ Fehler',
      tabGrab: 'Erfassen',
      tabHistory: 'Verlauf',
      tabCollections: 'Sammlungen',
      downloadHistory: 'Download-Verlauf',
      clearAll: 'Alle löschen',
      noDownloads: 'Noch keine Downloads',
      newCollectionPlaceholder: 'Sammlungsname...',
      addCollection: '+ Hinzufügen',
      noCollections: 'Noch keine Sammlungen',
      addSelectedImages: 'Ausgewählte Bilder hinzufügen',
      cloudUpload: 'Cloud-Upload',
      cloudDesc: 'Bilder in Cloud-Speicher hochladen.',
      cloudNote: 'Jeder Anbieter öffnet seine eigene OAuth-Seite.',
      customTheme: 'Benutzerdefinierte Themenfarbe',
      customPrimaryColor: 'Primärfarbe',
      resetColor: 'Zurücksetzen',
      walkthroughTitle: 'Willkommen bei Photo-Grab!',
      walkthroughStep1Title: 'Bilder auswählen',
      walkthroughStep1Desc: 'Klicke auf Bilder auf der Seite. Nutze den Extension Active Schalter.',
      walkthroughStep2Title: 'Herunterladen oder konvertieren',
      walkthroughStep2Desc: 'Nutze Download für Massendownloads. Aktiviere Photo Converter für die Symbolleiste.',
      walkthroughStep3Title: 'Verlauf und Sammlungen',
      walkthroughStep3Desc: 'Sieh den Download-Verlauf im Verlauf-Tab. Nutze Sammlungen zur Organisation.',
      walkthroughNext: 'Weiter',
      walkthroughDone: 'Loslegen!',
      walkthroughSkip: 'Überspringen'
    }
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = LANGUAGES;
}
